### ISSUE TITLE
Add dataset attribution to API responses

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#114]
For a query to `/api/timeseries`, it can be confusing to know where the datasets are coming from because there is no dataset source/attribution. Example: 

<http://plenar.io/v1/api/timeseries/?obs_date__ge=2014-01-01&dataset_name__ilike=%25311%25&agg=week>

returns ~15 datasets with "311" in the title: to figure out where "311_unified_data" comes from, a user would have to go searching through our list of datasets. 

While we're at it, could we add the human name, too?

**Comment by WillEngler** [comment]
Added metadata to `/timeseries` response in ef85cb2150bd16c123c2c2f542231ff32de5708f.
