### ISSUE TITLE
More than one empty filter field appears

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#125]
Occasionally when I change the resolution on an `/explore#detail` page (no filters entered), I get this: 

![image](https://cloud.githubusercontent.com/assets/1857606/4377866/2043a020-4353-11e4-9807-f4c36d05de76.png)

Then, if I click "Add Filter", I get three more:
![image](https://cloud.githubusercontent.com/assets/1857606/4377876/31e66d3a-4353-11e4-955a-3045777dfd41.png)

The problem does not seem reproducible (can't give you a URL) but happens every once in a while. I've seen it with three filter fields and with five.

**Comment by WillEngler** [comment]
There was a lot of weird stuff going on with the filters. Fixed at last over in the new [explorer repository](https://github.com/UrbanCCD-UChicago/plenario-explorer). 

The behavior is a tad different now. The user can only edit one filter at a time, and needs to click an "Add Filter" button to add it to the list of active filters.
