### ISSUE TITLE
Allow import of shapefile data

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#142]
A lot of data is tied to shapes like community area or police district. We need to think about how we want to import such shapefiles and make them available, and furthermore how to handle data tied to them.

**Comment by WillEngler** [comment]
Preliminary support for shapefile ingestion is up. Admins can add a shape dataset in the admin panel and users can perform some basic shape queries through new API endpoints. More to come!

**Comment by WillEngler** [comment]
As of today, users can submit ESRI shapefiles at http://plenar.io/add
