### ISSUE TITLE
Extending spatial resolution

### ISSUE THREAD

**Issue by fgregg** [UrbanCCD-UChicago/plenario#16]
One of the limitations for having high spatial resolution is that, with a uniform grid, higher resolutions dramatically increase the number of polygons the client has to render.

One possible solution is to use quad trees, to have adaptively higher resolution where the action is and low resolution where there's little going on.

![image006](https://cloud.githubusercontent.com/assets/536941/3362488/467a282c-fb0a-11e3-95ff-0c41a1e26cab.gif)

We'd set a minimum cell size, and a maximum cell count.

**Comment by WillEngler** [comment]
Valuable discussion at the early stage of the project, but a bit too open-ended to belong in the issues section now. Closing.
