### ISSUE TITLE
Weather data going back to 2011

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#165]
NOAA's LCD weather data goes back to 2005 with quality control - we should make sure we cover observations at least that far back. Right now it doesn't look like we have weather prior to about 2012, even in Chicago:

[This query](http://plenar.io/v1/api/detail/?dataset_name=cdph_environmental_complaints&obs_date__le=2011-12-10&weather=true) returns a failure. 

This is a priority from @brettjgoldstein - we've been telling people we have weather! Please let us know if there are issues with data quality before 2012 that we aren't aware of.

**Comment by lucaluca** [comment]
Changed this issue to 2011 per talks with @derekeder. I believe we're focusing on full coverage of daily observations and then following up with deeper (i.e. earlier) coverage of "hourly" observations for all areas of the US where we have data - please correct if I'm wrong.

**Comment by derekeder** [comment]
@lucaluca correct. We'll look in to going back further than 2011, but the goal is to first have daily observation coverage for the entire US.

**Comment by evz** [comment]
We're in the process of importing daily weather observations going back to July 1996 for the entire US right now. That should complete sometime this afternoon. @mccc will also start the process of importing the hourly weather observations going back that far for the areas that are covered by other datasets.

**Comment by mccc** [comment]
Hourly weather from Jan 2000-Dec 2014 for all relevant observation stations for current datasets should now be up. Still some parser glitches on a couple 1990s QCLCD datasets. We'll add 2015 shortly and try to ensure that each new day of QCLCD data for these stations is consistently added in a daily celery process.

**Comment by derekeder** [comment]
We now have data from January 2000. Closing.
