### ISSUE TITLE
Stop reimport of failed imports

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#170]
It looks like some datasets that initially fail to import (such as [Louisville crime](http://plenar.io/admin/dataset-status/?source_url_hash=5babed4542bcdd65b3e11e17a194ccd8)) keep trying to import every day with the same result. We should perhaps limit this to 1-2 re-attempts to reduce load.

**Comment by brettjgoldstein** [comment]
Why do they fail ?

On Thu, Jan 15, 2015 at 3:30 PM, Jonathan Giuffrida <notifications@github.com> wrote:

It looks like some datasets that initially fail to import (such as Louisville crime<http://plenar.io/admin/dataset-status/?source_url_hash=5babed4542bcdd65b3e11e17a194ccd8>) keep trying to import every day with the same result. We should perhaps limit this to 1-2 re-attempts to reduce load.

**Comment by lucaluca** [comment]
Usually type inference issues. One was because of an extra column in some lines. Several failed during their first import in 2015 - likely a data change that we can fix by re-importing.
