### ISSUE TITLE
Links don't work with explorer

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#171]
When using a link shortener like http://bit.ly/1sYSsPz, I get a blank Explore page:

![image](https://cloud.githubusercontent.com/assets/1857606/5841777/21df4568-a165-11e4-8eeb-726968b2e62d.png)

This also happens when I use the actual link, http://plenar.io/explore#aggregate/obs_date__le=2015/01/21&obs_date__ge=2005/01/21&location_geom__within={"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[-73.91543626785278,40.90209584891611],[-73.81106615066528,40.853293085675155],[-73.78634691238403,40.79405848578321],[-73.72454881668091,40.73477098967238],[-73.75201463699341,40.62750334315296],[-73.77810716629027,40.58997103470645],[-74.01019334793091,40.52006312552015],[-74.22442674636841,40.509622849596695],[-74.21893358230591,40.562851259102054],[-74.19558763504028,40.6410514961004],[-74.06649827957152,40.656680564044166],[-74.00607347488403,40.75974059207392],[-73.91543626785278,40.90209584891611]]]}}&agg=week.

**Comment by derekeder** [comment]
Looked in to this. Seems like URL shorteners don't escape the commas in our GeoJSON boundary definition. The Explorer doesn't seem to be able to handle this.

#### Before URL shortening:

http://plenar.io/explore#detail/obs_date__le=2015%2F01%2F23&obs_date__ge=2014%2F10%2F25&location_geom__within={%22type%22%3A%22Feature%22%2C%22properties%22%3A{}%2C%22geometry%22%3A{%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-87.71100999321789%2C41.891032732083765%5D%2C%5B-87.71100999321789%2C41.90483228960834%5D%2C%5B-87.68697740044445%2C41.90483228960834%5D%2C%5B-87.68697740044445%2C41.891032732083765%5D%2C%5B-87.71100999321789%2C41.891032732083765%5D%5D%5D}}&agg=week&dataset_name=crimes_2001_to_present&resolution=500

#### After

http://plenar.io/explore#detail/obs_date__le=2015/01/23&obs_date__ge=2014/10/25&location_geom__within={%22type%22:%22Feature%22,%22properties%22:{},%22geometry%22:{%22type%22:%22Polygon%22,%22coordinates%22:%5B%5B%5B-87.71100999321789,41.891032732083765%5D,%5B-87.71100999321789,41.90483228960834%5D,%5B-87.68697740044445,41.90483228960834%5D,%5B-87.68697740044445,41.891032732083765%5D,%5B-87.71100999321789,41.891032732083765%5D%5D%5D}}&agg=week&dataset_name=crimes_2001_to_present&resolution=500

I'll look in to making the URL parsing in the Explorer a bit more robust to handle this case.

**Comment by derekeder** [comment]
The backbone.js router is the issue here. It doesn't know how to properly handle GeoJSON in the URL. Look in to using this plugin: https://github.com/jhudson8/backbone-query-parameters

**Comment by WillEngler** [comment]
Fixed. The routes in the Explorer are a bit different now, so the above links won't work verbatim, but try out 
http://plenar.io/explore/event/food_inspections?location_geom__within=%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-87.65074968338013%2C41.80510182643331%5D%2C%5B-87.65074968338013%2C41.87774145109676%5D%2C%5B-87.60131120681761%2C41.87774145109676%5D%2C%5B-87.60131120681761%2C41.80510182643331%5D%2C%5B-87.65074968338013%2C41.80510182643331%5D%5D%5D%7D%7D&obs_date__ge=2016-02-02&obs_date__le=2016-05-02

which also works with Google's link shortener: http://goo.gl/Z9u8ya
