### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by natnaell** [UrbanCCD-UChicago/plenario#175]
I attempted to upload a dataset (https://data.lacity.org/A-Safe-City/LAPD-Crime-and-Collision-Raw-Data-2014/eta5-h8qx) but received a 504 gateway timeout. When I tried to resubmit, plenario said the data set was already loaded but I highly doubt it.

**Comment by brettjgoldstein** [comment]
any thoughts on this?

**Comment by derekeder** [comment]
@natnaell @brettjgoldstein we're looking in to it.

**Comment by derekeder** [comment]
Google recently disabled sending email over SSL over port 465, which is what we were using for sending confirmation messages when someone submits a new dataset to plenar.io.

We updated the email configuration to send via [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security) using port 587

fixed via 2e56291c5bc79c3cdb6bbb3e3d73ac1d5c2f8f05
