### ISSUE TITLE
stratify /detail-aggregate by census block

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#176]
A project I am working on involves gathering counts over time by census block. Currently this requires requesting data from `/detail-aggregate` with the query parameter `census_block_ilike` ([Example](http://plenar.io/v1/api/detail-aggregate/?dataset_name=311_service_requests_pot_holes_reported&obs_date__ge=2014-03-23&census_block__ilike=17031839100%25%data_type=csv)). When gathering data for all census blocks in Chicago, this takes 46,000 queries, and requires that my list of census blocks be exactly the same as Plenario's. It would be great if the user could add something like a `spatial_agg` parameter that could accept any piece of the Census block ID (block, tract, county, state) and return the results aggregated by that spatial unit as well as the existing temporal aggregation.

**Comment by brettjgoldstein** [comment]
Is something like this hard?


Brett Goldstein
Senior Fellow in Urban Science
Harris School of Public Policy
University of Chicago
@bjgol




On May 1, 2015 at 12:15:06 PM, Jonathan Giuffrida (notifications@github.com<mailto:notifications@github.com>) wrote:

A project I am working on involves gathering counts over time by census block. Currently this requires requesting data from /detail-aggregate with the query parameter census_block_ilike (Example<http://plenar.io/v1/api/detail-aggregate/?dataset_name=311_service_requests_pot_holes_reported&obs_date__ge=2014-03-23&census_block__ilike=17031839100%25%data_type=csv>). When gathering data for all census blocks in Chicago, this takes 46,000 queries, and requires that my list of census blocks be exactly the same as Plenario's. It would be great if the user could add something like a spatial_agg parameter that could accept any piece of the Census block ID (block, tract, county, state) and return the results aggregated by that spatial unit as well as the existing temporal aggregation.

**Comment by derekeder** [comment]
We're going to work on making the /timeseries endpoint more efficient ( #145 ) before exploring this. 

Generally, aggregating by both time and geography would lead to a very large response size which we would likely have to limit, so it wouldn't necessarily reduce the time it takes to perform a query like this.
