### ISSUE TITLE
/timeseries dataset_name__in pulls all datasets

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#177]
When I go to

http://plenar.io/v1/api/timeseries/?agg=month&dataset_name__in=311_service_requests_abandoned_vehicles%2C311_service_requests_alley_lights_out%2C311_service_requests_tree_trims%2C311_service_requests_street_lights_all_out%2C311_service_requests_pot_holes_reported%2C311_service_requests_garbage_carts%2C311_service_requests_sanitation_code_complaints%2C311_service_requests_graffiti_removal%2C311_service_requests_vacant_and_abandoned_building%2C311_service_requests_tree_debris%2C311_service_requests_rodent_baiting%2C311_service_requests_street_lights_one_out&obs_date__ge=2011-01-01&census_block__like=17031010100%25

meta.query says the request was for every dataset in plenario. Seems to be an issue with the `dataset_name__in` argument, occurs even when I request only one dataset. When I change the parameter to `dataset_name`, it only returns the dataset I request, though meta.query still says I used `dataset_name__in` and asked for all datasets.

**Comment by lucaluca** [comment]
Has anyone been able to take a look at this? I imagine it significantly increases the load on the servers, and I keep getting 504 timeouts.

**Comment by derekeder** [comment]
@lucaluca we'll look in to it this week.

**Comment by brettjgoldstein** [comment]
Is there an update to this issue?

**Comment by derekeder** [comment]
We'll get this fixed today.

On Sun, Jun 21, 2015 at 8:48 AM, brettjgoldstein <notifications@github.com>
wrote:

> Is there an update to this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UrbanCCD-UChicago/plenario/issues/177#issuecomment-113903191>
> .
>



-- 
Derek Eder
@derekeder <https://twitter.com/#!/derekeder>
derek.eder@gmail.com
derekeder.com

**Comment by evz** [comment]
@lucaluca This should be deployed now
