### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by natnaell** [UrbanCCD-UChicago/plenario#178]
The example link for Midway hourly weather isn't returning values.
http://plenar.io/v1/api/weather/hourly/?wban_code=14819&datetime__ge=2015-05-10

**Comment by derekeder** [comment]
Thanks for letting us know. We'll look in to it.

FYI @mccc @evz

**Comment by evz** [comment]
Hey @natnaell this should be fixed now. Thanks for the heads up!
