### ISSUE TITLE
Weather data not updating to date

### ISSUE THREAD

**Issue by jiajunshen** [UrbanCCD-UChicago/plenario#179]
Plenario appears to still only offer weather data through to 21 April 2015 for Chicago (wban_code: 04807 04831 14819 94846).

Example: http://plenar.io/v1/api/weather/hourly/?wban_code=14819&datetime__ge=2015-04-20

This also related to #178 .

**Comment by brettjgoldstein** [comment]
Any updates on this ?

Sent using CloudMagic<https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.2>

On Thu, May 21, 2015 at 11:44 PM, Jiajun Shen <notifications@github.com> wrote:

Plenario appears to still only offer weather data through to 21 April 2015 for Chicago (wban_code: 04807 04831 14819 94846).

Example: http://plenar.io/v1/api/weather/hourly/?wban_code=14819&datetime__ge=2015-04-20

This also related to #178<https://github.com/UrbanCCD-UChicago/plenario/issues/178> .

**Comment by derekeder** [comment]
We're looking in to this. We'll have an update today.

**Comment by evz** [comment]
Hey this should be fixed. NOAA moved their bulk download page. You should be able to see the new stuff here (I changed the date back one day so you don't get the cached version) http://plenar.io/v1/api/weather/hourly/?wban_code=14819&datetime__ge=2015-04-19

**Comment by jiajunshen** [comment]
Thanks a lot for the quick fix!
I quickly checked the link you provided, but it appears to only offer
weather data until May 18th. Is the weather data between May 18th to May
21st available on NOAA website?

Thanks!

Jiajun

On Fri, May 22, 2015 at 3:56 PM, Eric van Zanten <notifications@github.com>
wrote:

> Hey this should be fixed. NOAA moved their bulk download page. You should
> be able to see the new stuff here (I changed the date back one day so you
> don't get the cached version)
> http://plenar.io/v1/api/weather/hourly/?wban_code=14819&datetime__ge=2015-04-19
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UrbanCCD-UChicago/plenario/issues/179#issuecomment-104765302>
> .
>



-- 
Sincerely,
------------------------------------------------
Jiajun Shen
Department of Computer Science
The University of Chicago
Chicago, IL, USA

**Comment by derekeder** [comment]
@jiajunshen the QCD from NOAA is delayed by a few days. To get the freshest weather observations, we have a separate API endpoint for METAR data: http://plenar.io/api-docs#collapse-api-weather-metar

**Comment by lucaluca** [comment]
@derekeder thanks for this. Currently I can only see QCD data as late as 5/20, but the [NCDC site](http://www.ncdc.noaa.gov/qclcd/QCLCD?prior=N) currently has data up to 5/24 - are we definitely updating every day? Maybe they were off for the holiday...

**Comment by evz** [comment]
Hey, so this should be really, really fixed this time. Check it here: http://plenar.io/v1/api/weather/hourly/?wban_code=14819&datetime__ge=2015-04-18
