### ISSUE TITLE
API timeout error and slow loading

### ISSUE THREAD

**Issue by Makosak** [UrbanCCD-UChicago/plenario#180]
When pulling some tract-level data from the API, it times out in error. When pulling block-level data, the downloading stops after 1.4% complete (after an hour). I know that service/internet speed is partly an issue, but the timeout error and long loading are creating a bottleneck. I've been able to successfully use other APIs (Google, ESRI) without the same error.

**Pulling:** 'crimes_2001_to_present', '311_service_requests_vacant_and_abandoned_building', and
  '311_service_requests_rodent_baiting'

**Block-level holding up at:**
downloading data for block 649 of 46324 (1.4% done, 401 minutes remaining))

**Tract-level timeout error:**
data preparation complete  
downloading data...---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-4-0203db00389b> in <module>()
      3   'tractce10', ['crimes_2001_to_present', 
      4   '311_service_requests_vacant_and_abandoned_building',
----> 5   '311_service_requests_rodent_baiting'])

/Users/Makosak/code/blobs/blobs.pyc in **init**(self, census_data, level, shp, shp_id, datasets, temporal_agg, time_start, time_end)
    205             elif level == 'block':
    206                 url = self.prefix_url + '&census_block=' + str(final.ix[t, 0])
--> 207             cr = pd.read_csv(url)
    208             for name in datasets:
    209                 try:

/Users/Makosak/anaconda/lib/python2.7/site-packages/pandas/io/parsers.pyc in parser_f(filepath_or_buffer, sep, dialect, compression, doublequote, escapechar, quotechar, quoting, skipinitialspace, lineterminator, header, index_col, names, prefix, skiprows, skipfooter, skip_footer, na_values, na_fvalues, true_values, false_values, delimiter, converters, dtype, usecols, engine, delim_whitespace, as_recarray, na_filter, compact_ints, use_unsigned, low_memory, buffer_lines, warn_bad_lines, error_bad_lines, keep_default_na, thousands, comment, decimal, parse_dates, keep_date_col, dayfirst, date_parser, memory_map, float_precision, nrows, iterator, chunksize, verbose, encoding, squeeze, mangle_dupe_cols, tupleize_cols, infer_datetime_format, skip_blank_lines)
    463                     skip_blank_lines=skip_blank_lines)
    464 
--> 465         return _read(filepath_or_buffer, kwds)
    466 
    467     parser_f.__name__ = name

/Users/Makosak/anaconda/lib/python2.7/site-packages/pandas/io/parsers.pyc in _read(filepath_or_buffer, kwds)
    227 
    228     filepath_or_buffer, _ = get_filepath_or_buffer(filepath_or_buffer,
--> 229                                                    encoding)
    230 
    231     if kwds.get('date_parser', None) is not None:

/Users/Makosak/anaconda/lib/python2.7/site-packages/pandas/io/common.pyc in get_filepath_or_buffer(filepath_or_buffer, encoding)
    116 
    117     if _is_url(filepath_or_buffer):
--> 118         req = _urlopen(str(filepath_or_buffer))
    119         return maybe_read_encoded_stream(req, encoding)
    120 

/Users/Makosak/anaconda/lib/python2.7/urllib2.pyc in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    152     else:
    153         opener = _opener
--> 154     return opener.open(url, data, timeout)
    155 
    156 def install_opener(opener):

/Users/Makosak/anaconda/lib/python2.7/urllib2.pyc in open(self, fullurl, data, timeout)
    435         for processor in self.process_response.get(protocol, []):
    436             meth = getattr(processor, meth_name)
--> 437             response = meth(req, response)
    438 
    439         return response

/Users/Makosak/anaconda/lib/python2.7/urllib2.pyc in http_response(self, request, response)
    548         if not (200 <= code < 300):
    549             response = self.parent.error(
--> 550                 'http', request, response, code, msg, hdrs)
    551 
    552         return response

/Users/Makosak/anaconda/lib/python2.7/urllib2.pyc in error(self, proto, _args)
    473         if http_err:
    474             args = (dict, 'default', 'http_error_default') + orig_args
--> 475             return self._call_chain(_args)
    476 
    477 # XXX probably also want an abstract factory that knows when it makes

/Users/Makosak/anaconda/lib/python2.7/urllib2.pyc in _call_chain(self, chain, kind, meth_name, _args)
    407             func = getattr(handler, meth_name)
    408 
--> 409             result = func(_args)
    410             if result is not None:
    411                 return result

/Users/Makosak/anaconda/lib/python2.7/urllib2.pyc in http_error_default(self, req, fp, code, msg, hdrs)
    556 class HTTPDefaultErrorHandler(BaseHandler):
    557     def http_error_default(self, req, fp, code, msg, hdrs):
--> 558         raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    559 
    560 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 504: Gateway Time-out

**Comment by evz** [comment]
What is ``self.prefix_url`` up there? This will help us narrow in on which endpoint is timing out.

**Comment by derekeder** [comment]
The speed of the `/v1/api/timeseries/` endpoint is a known issue (#145). Writing up some thoughts over there.
