### ISSUE TITLE
PlenarioETLError: Missing data for column

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#181]
The [Chicago crimes dataset](http://plenar.io/admin/dataset-status/?source_url_hash=faefd72e955754eb1ea74f16e4f34e50) (admin access required) keeps failing update because of a missing data error, for a non-essential field (community area). We may want to have it issue a warning instead, or a silent error, and continue with the update if a non-essential field is missing.

**Comment by WillEngler** [comment]
I'm gonna move discussion for this into #184
