### ISSUE TITLE
Metar Data Missing Precipitation

### ISSUE THREAD

**Issue by natnaell** [UrbanCCD-UChicago/plenario#183]
The Metar dataset has no values for hourly precipitation (precip_1hr) even for hours where it has rained. Thanks.

**Comment by derekeder** [comment]
@natnaell thanks - we'll take a look at this.

**Comment by brettjgoldstein** [comment]
This is pretty critical as we are getting the weather site prepped to launch.


Brett Goldstein
Senior Fellow in Urban Science
Harris School of Public Policy
University of Chicago
@bjgol




On August 18, 2015 at 3:50:08 PM, Derek Eder (notifications@github.com<mailto:notifications@github.com>) wrote:

@natnaell<https://github.com/natnaell> thanks - we'll take a look at this.

**Comment by evz** [comment]
I just deployed a fix that should address this issue. I'll wait until it rains again and then close this it if it seems to be working.
