### ISSUE TITLE
Missing kombu requirement

### ISSUE THREAD

**Issue by TanuMalik** [UrbanCCD-UChicago/plenario#195]
I have Celery installed correctly, but running
```
celery -A plenario.celery_app worker --loglevel=info &
```

Gives the following error:
```
[2] 19006
ubuntu@ip-172-31-7-130:~/EDE/plenario$ Traceback (most recent call last):
  File "/usr/local/bin/celery", line 7, in <module>
    from celery.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/celery/__init__.py", line 131, in <module>
    from celery import five  # noqa
  File "/usr/local/lib/python2.7/dist-packages/celery/five.py", line 20, in <module>
    from kombu.five import monotonic
ImportError: No module named kombu.five
```
Requirements.txt is missing kombu.

**Comment by WillEngler** [comment]
That's curious. Kombu is included in Celery's dependencies (https://github.com/celery/celery/blob/master/requirements/default.txt), so pip should pick it up (in theory). I'm gonna call this a one-off unless we see others have a problem with this.

In any event, I'm glad you got Celery up!
