### ISSUE TITLE
Download of chunks

### ISSUE THREAD

**Issue by TanuMalik** [UrbanCCD-UChicago/plenario#199]
Plenario downloads in 1KB sized chunks unlike what the documentation points stating at 1MB. This makes it quite slow for large shape files like the one that I am trying to insert which is 405MB.  

The documentation of iter_request at http://docs.python-requests.org/en/latest/api/ 
states chunk_size is in bytes and not kilobytes. Plenario is using a value of 1024 not 1024*1024.

**Comment by WillEngler** [comment]
Looks like I didn't read the docs closely enough; good catch!

For issues like this, please feel free to make the fix and send in a tiny pull request.
