### ISSUE TITLE
Provide assistance figuring out relevant filter values

### ISSUE THREAD

**Issue by levyj** [UrbanCCD-UChicago/plenario#203]
Users may have a hard time figuring out how to build filters that get at what they need because it can require some knowledge about the dataset columns and the values used.  As an example, _I created_ the dataset behind "City of Chicago: Transportation Department Permits" and _I_ could not do a meaningful filter without going back to the dataset.  Some possible improvements:
- Provide a link to the original dataset (not just the download).
- Show some sample rows.
- Bring in the original human-readable column names and/or column descriptions.
- Provide a pick list of values for a column if it is short enough.

**Comment by WillEngler** [comment]
:+1:

Agreed. Very unintuitive now.

**Comment by levyj** [comment]
Thanks.  By the way, providing the link to the dataset -- and exposing it or just the 4x4 (Socrata unique ID for a view) through the API -- would open up some options for us on Open Grid.

**Comment by stevevance** [comment]
I really like the idea of sample rows. The CTA bus ridership data that my ChiHackNight group is using has a lot of possible values for the 
- Bus routes
- Street name the stop is on
- Cross street that the stop is at

**Comment by lw334** [comment]
@levyj Hello Jonathan, you'll now be able to get the view_url from the /dataset API.
