### ISSUE TITLE
Explore page doesn't apply filters to the chart

### ISSUE THREAD

**Issue by lucaluca** [UrbanCCD-UChicago/plenario#216]
I'm running queries on Chicago crime:

[Query](http://plenar.io/explore#detail/dataset_name=crimes_2001_to_present&obs_date__le=2016%2F02%2F05&obs_date__ge=2001%2F01%2F01&agg=year&resolution=1000&iucr=0110&arrest=yes)

The points on the map are filtered, but the chart is not - it shows 5+ million records no matter what filters I apply to the data. It does update when I change the time period.

**Comment by WillEngler** [comment]
Huge oversight on my part. For the aggregation endpoints (like `/detail-aggregate` and `/grid`) I construct the column filters but fail to pass them on to the database along with the rest of the aggregation. Should be a quick fix. Thanks so much for bringing it to my attention.

**Comment by TanuMalik** [comment]
Hi Will,

I mentioned about this wrt to downloads. I never got around checking it. 

If you apply a filter, I think the download dataset does not correspond to the filter. 

Tanu

**Comment by lucaluca** [comment]
Thanks, @WillEngler . On the same subject, are there plans to allow query parameters for the polygon_filter endpoint? For instance, to pull crimes with IUCR=0110 (homicide) by Chicago community area. Would really help with a project I'm working on, and would be great for [blobs](https://github.com/ChicagoHarris/blobs).

**Comment by WillEngler** [comment]
@lucaluca Yeah, that's in the works right now. I'll drop you a line when it's live (probably next week, along with public shape submission). The point/shape endpoints are pretty unstable at the moment, but my policy is to push up our experiments so that people can play with them.

**Comment by WillEngler** [comment]
Looks like that bug was limited to `/detail-aggregate`. Fix is live. The awkward map zoom we're seeing on @lucaluca's example deserves a separate issue though. And @TanuMalik, could you specify reproduction steps for for the download bug you saw in a new issue so that I can diagnose it?

**Comment by WillEngler** [comment]
Looking into the zoom, that grid query turns up a little cluster of 5 homicides southeast of West Plains, Missouri. Looking at Chicago's crime dataset, there actually are ~230 records geocoded to Southern Missouri. ¯\_(ツ)_/¯

**Comment by lucaluca** [comment]
The map zoom isn't really an issue - it's caused by five crimes that were mis-geocoded to southern Missouri:

![image](https://cloud.githubusercontent.com/assets/1857606/12860749/4d6f8162-cc24-11e5-889a-631f3aa8ed6c.png)

We see this every so often because of issues with the raw data. One solution we discussed a while ago was determining the bounding box that would cover 99%, rather than 100%, of the data, but this is computationally expensive and not really essential anyway. It's better to let DoIT know of the issue and let them fix it.
