### ISSUE TITLE
Human-friendly names (aliases)

### ISSUE THREAD

**Issue by tomschenkjr** [UrbanCCD-UChicago/plenario#222]
When pulling from Socrata, the names associated with each data set are pulled from the data set title. While this makes sense in Socrata, the titles can be not user-friendly when being used, e.g., Crimes_2001_to_present. While we can fix these issues on the app side, seems like this might be a universal problem where it could be useful to present a human-readable alias (e.g., "Crimes") that applications can refer to.

(Will - this came up as we were thinking about those annoyances we're hitting. This came up as an issue in the CUT Group testing).

**Comment by WillEngler** [comment]
Great, I'm interested to see how we can make this more intuitive. Here's what we do right now:

As you probably know, our metadata endpoint returns the machine-formatted name that users can form queries around, as well as a human-readable name.

Like this:
```
dataset_name: "311_service_requests_garbage_carts",
human_name: "311 Service Requests - Garbage Carts",
```
When someone submits a Socrata dataset, we pull `human_name` from the `name` attribute of the Socrata views API. The submitter can choose a different name if she chooses. Then we slugify `human_name` to get the `dataset_name`.

What could we do on our side to help?

**Comment by tomschenkjr** [comment]
Ah, I don’t think I realized that was editable upon submission. I took the auto-fill as required.

I think that’s it, then! I’ll re-open if I missed a nuance.
