### ISSUE TITLE
Expand column filtering syntax

### ISSUE THREAD

**Issue by WillEngler** [UrbanCCD-UChicago/plenario#223]
To apply filtering operators to columns in Plenario API calls, we ask users to use Django-like double underscore syntax like `?iucr__ne=0110&ward__ge=48`. This has served us well, and isn't going away any time soon. But it has two problems:

1. Because every filter is an independent key-value pair, I don't see any way to introduce OR operations.
2. Now that we allow dynamic joins in some queries, we need to disambiguate which dataset a column filter applies to in the case of name collisions. (e.g. if you're joining a shape dataset to an event dataset and only want shapes whose `name` matches some glob pattern, you have to say `name__ilike=%foo%.` How do you signal your intent that that filter should only apply to the shape dataset if the event dataset also has a `name` attribute? )

@ayang7 and @samkqx are working on new syntax to solve these problems. It will let you specify filters for each dataset in your query, so something like `crimes_2001_to_present__filters={}&boundaries_neighborhoods__filters={}` where the values are JSON representing a tree of conjunctions and disjunctions.

@ayang7 could you post an example of the JSON syntax?

**Comment by ayang7** [comment]
JSON syntax:
condition_tree
{
  "op": [STMT, AND, OR]
  "val": [{"left": condition_tree, "right": condition_tree}, {"col_name": string, "val": value}]
}

"AND" and "OR" conditions are represented as trees. Each node of the tree is tagged as one of an "AND", an "OR", or a "STMT" by the "op" field. Each node also includes a "val" field that will contain either (for AND and OR nodes) references to "left" and "right" child nodes, or (for STMT nodes, which are leaf nodes) a "col_name" and a target "val" that represents a single condition. For example:
{
  "op: "AND"
  "val": {
             "left": {"op": "STMT", "val": {"col_name": "city", "val": "CHICAGO"} }
             "right": {
                          "op": "OR"
                          "val": {
                                     "left":  {"op": "STMT", "val": {"col_name": "neighborhood", "val": "HYDE PARK"} }
                                     "right":  {"op": "STMT", "val": {"col_name": "neighborhood", "val": "KENWOOD"} }
                                   }
                        }
           }
}
corresponds to 
"(city = "Chicago") AND ((neighborhood = "HYDE PARK") OR (neighborhood = "KENWOOD"))

**Comment by HeyZoos** [comment]
Resolved as of PR #240
