### ISSUE TITLE
Bad link on plenar.io example page

### ISSUE THREAD

**Issue by mjwilde** [UrbanCCD-UChicago/plenario#224]
On this page:
   http://plenar.io/examples#collapse-ex-1
...under "Tell me the story of 700 Howard street..." the link under the "View in Data Explorer" map image is broken (.../aggregate/obs_date... should be .../aggregate?obs_date... )

http://plenar.io/explore/discover/aggregate/obs_date__ge=2009%2F09%2F23&obs_date__le=2014%2F09%2F23&location_geom__within=%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-122.401578%2C37.789506%5D%2C%5B-122.408574%2C37.784113%5D%2C%5B-122.401857%2C37.77889%5D%2C%5B-122.394948%2C37.784351%5D%2C%5B-122.401578%2C37.789506%5D%5D%5D%7D%7D&agg=week

should be:

http://plenar.io/explore/discover/aggregate?obs_date__ge=2009%2F09%2F23&obs_date__le=2014%2F09%2F23&location_geom__within=%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B-122.401578%2C37.789506%5D%2C%5B-122.408574%2C37.784113%5D%2C%5B-122.401857%2C37.77889%5D%2C%5B-122.394948%2C37.784351%5D%2C%5B-122.401578%2C37.789506%5D%5D%5D%7D%7D&agg=week

**Comment by WillEngler** [comment]
Thanks for the heads-up! We'll pull that in.
