### ISSUE TITLE
weather data update

### ISSUE THREAD

**Issue by sparker6** [UrbanCCD-UChicago/plenario#279]
hello - for WBAN =13739 for any weather data past 1/24/17 for hourly weather data does not seem to currently populate.

### all observations for the day populate: 
http://plenar.io/v1/api/weather/hourly/?wban_code=13739&datetime__ge=2017-01-22

### observations on 1/23/17 and beyond are not populated, for instance: 
http://plenar.io/v1/api/weather/hourly/?wban_code=13739&datetime__ge=2017-01-26

**Comment by HeyZoos** [comment]
Hi Susan, I'll reingest that month and see if that fixes things

**Comment by vforgione** [comment]
@sparker6, was this resolved?

**Comment by sparker6** [comment]
Hi everyone --- yes -- thank you!

**Comment by vforgione** [comment]
@sparker6 thanks for the quick response - I'll close the issue.
