### ISSUE TITLE
Is runserver.py missing? [plenario install/run question]

### ISSUE THREAD

**Issue by niceyeti** [UrbanCCD-UChicago/plenario#282]
From the main plenario README.md: "Finally, run the server: python runserver.py".

Is runserver.py missing? I can't find this file anywhere in the repo. Thank you for any help!

**Comment by HeyZoos** [comment]
Yep, sorry I need to update the README. You can start the server by using the manage.py file. `./manage.py runserver` or `python manage.py runserver`.

**Comment by niceyeti** [comment]
Thanks! Starting that way, an exception is thrown for "ImportError: No module named flask_script" from manage.py. Some of the online commentary claims the import pattern "flask.exthook" is deprecated or out of date. But I just commented out the two lines referring to "ExtDeprecationWarning" and it runs like a charm.
