### ISSUE TITLE
Some shape datasets return empty GeoJSON FeatureCollection

### ISSUE THREAD

**Issue by brlodi** [UrbanCCD-UChicago/plenario#297]
Several shape datasets, when accessed via the `/shapes/{dataset_name}` endpoint, return an empty FeatureCollection as below, despite their metadata indicating a non-zero number of contained shapes.
```json
{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [

]
}
```

A non-exhaustive list of affected dataset names:

- `parks_public_art_shapefiles`
- `senior_centers`
- `public_technology_resources`

All affected datasets appear to have ZIP sources.

**Comment by HeyZoos** [comment]
These datasets were empty due to ETL errors which were resolved by #301
