### ISSUE TITLE
Docker compose installation - does not add CSV data

### ISSUE THREAD

**Issue by gioppoluca** [UrbanCCD-UChicago/plenario#338]
I've installed the docker compose distribution and I'm receiving this error:
server_1    | 2018-03-20 10:49:58 - INFO - werkzeug._log:87 - 158.102.240.178 - - [20/Mar/2018 10:49:58] "POST /admin/add?dataset_url=https%3A%2F%2Fdata.cityofchicago.org%2FPublic-Safety%2FCrimes-2010%2Fq4de-h6yq HTTP/1.1" 200 -
worker_1    | [2018-03-20 10:49:58,608: INFO/PoolWorker-1] Begin. (name: "crimes_2010_2")
worker_1    | [2018-03-20 10:49:58,608: INFO/PoolWorker-1] Begin. (name: "crimes_2010_2")
worker_1    | [2018-03-20 10:49:58,623: ERROR/PoolWorker-1] Task plenario.tasks.add_dataset[215b1370-5705-41c2-abc8-7ef3e861faab] raised unexpected: InvalidRequestError('This Session\'s transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.DataError) Geometry type (Point) does not match column type (Polygon)\n [SQL: \'UPDATE meta_master SET bbox=ST_GeomFromEWKT(%(bbox)s), column_names=%(column_names)s WHERE meta_master.source_url_hash = %(meta_master_source_url_hash)s\'] [parameters: {\'bbox\': \'0101000020E6100000023164D064D62040C65455C3D9A94640\', \'column_names\': \'{"sensor": "VARCHAR", "time": "TIMESTAMP WITHOUT TIME ZONE", "status": "VARCHAR", "streamcode": "VARCHAR", "longitude": "DOUBLE PRECISION", "latitude": "DOUBLE PRECISION"}\', \'meta_master_source_url_hash\': \'53e2b11daf436920a92044d04b111d1d\'}]',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 367, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 622, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/plenario/tasks.py", line 64, in add_dataset
worker_1    |     meta = get_meta(name)
worker_1    |   File "/app/plenario/tasks.py", line 38, in get_meta
worker_1    |     result = query.first()
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2755, in first
worker_1    |     ret = list(self[0:1])
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
worker_1    |     return list(res)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
worker_1    |     return self._execute_and_instances(context)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
worker_1    |     close_with_result=True)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
worker_1    |     **kw
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
worker_1    |     conn = self.session.connection(**kw)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 998, in connection
worker_1    |     execution_options=execution_options)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
worker_1    |     engine, execution_options)
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
worker_1    |     self._assert_active()
worker_1    |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
worker_1    |     % self._rollback_exception
worker_1    | sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.DataError) Geometry type (Point) does not match column type (Polygon)
worker_1    |  [SQL: 'UPDATE meta_master SET bbox=ST_GeomFromEWKT(%(bbox)s), column_names=%(column_names)s WHERE meta_master.source_url_hash = %(meta_master_source_url_hash)s'] [parameters: {'bbox': '0101000020E6100000023164D064D62040C65455C3D9A94640', 'column_names': '{"sensor": "VARCHAR", "time": "TIMESTAMP WITHOUT TIME ZONE", "status": "VARCHAR", "streamcode": "VARCHAR", "longitude": "DOUBLE PRECISION", "latitude": "DOUBLE PRECISION"}', 'meta_master_source_url_hash': '53e2b11daf436920a92044d04b111d1d'}]

Seems strange any hints on why there is this behaviour?
Thanks

**Comment by HeyZoos** [comment]
Hello Luca, unfortunately there isn't anything that jumps out at me right away. I'll try and ingest your dataset locally as well and see if I can find the issue.

**Comment by HeyZoos** [comment]
It seemed to ingest alright for me (this is the most unhelpful thing to say I know), so I'll lay out the steps I followed here and we can see if we diverged anywhere.

1) `Add Data`
2) Set `Observation Date` to `date`
3) Set `Latitude` to `latitude`
4) Set `Longitude` to `longitude`
5) Submitted for approval
6) Logged in with default credentials `plenario@email.com` and password `changemeplz`
7) Click on `Admin` then `View Datasets`
8) Reviewed and approved it without making any changes

After that I just waited and it ingested the data for me. Let me know how it goes!

**Comment by gioppoluca** [comment]
It does not work since the code in the "master" create the "master_meta" table with bbox of type Polygon and than the code tries to place a Point inside.
I've changed the column to type GEOMETRY and all works.
Also the web interface has hard coded the pointer to the plenar.io web site so no matter what you place in the installed instance it will never show you anything.
Maybe for that a config variable in settings of something like that could be an option.
Placing the plenar-explorer as an included JS to work with could also be a good idea.
