### ISSUE TITLE
Finding changes

### ISSUE THREAD

**Issue by evz** [UrbanCCD-UChicago/plenario#78]
I have finished implementing all of the new code that @jiajunshen wrote for the update process. The one thing that we need to still work out is calculating the changes in the incoming data (vs what's already stored in the ``dat`` table) for a given dataset. 

The assumption we made previously was that all of the duplicates would be eliminated so that when you run the join between the ``src`` table and the ``dat`` table, the keys that it returns are unique. That is no longer true because we are keeping all of the duplicate versions and just numbering them.

@svetlozarn How would you recommend comparing the incoming source data with what's already in the database given the new update strategy?

**Comment by WillEngler** [comment]
No longer relevant with new ETL
